### ISSUE TITLE
maximum update depth exceeded on custom tooltips demo

### ISSUE THREAD

**Issue by jharris4** [tannerlinsley/react-charts#37]
Hi, this is a great library! I've built something similar in the past so I'm definitely keeping an eye on this repo. ;-)

I was just playing with your demos, and the custom tooltip example seems to crash fairly quickly/often: https://react-charts.js.org/examples/custom-tooltip

```
vendors~main.d211a9cb.js:1 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:169683
    at u (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:169786)
    at eu (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:264447)
    at ca (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:225230)
    at https://react-charts.js.org/main.651d5ede.js:1:41784
    at bi (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:244545)
    at qi (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:251507)
    at Vi (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:254256)
    at https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:267460
    at Object.t.unstable_runWithPriority (https://react-charts.js.org/templates/vendors~main.d211a9cb.js:1:278230)
```

`The full text of the error you just encountered is:`

```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

This was on `Chrome Version 74.0.3729.169`

There were also quite a lot of these errors prior to the crash:

`Error: <rect> attribute height: Expected length, "NaN".`
`Error: <rect> attribute y: Expected length, "NaN".`

You might want to consider throwing some error boundaries into the demos as well, using `componentDidCatch`... ;-)

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version. Thanks for finding this!
